# Place configuration for solr_wrapper here
#
# Specify the port to run solr on
# port: 8983
#
# Specify a version of Solr to download
# version: 7.3.1
#
# Create a collection when starting solr
version: 7.3.1
collection:
  dir: /vagrant/project-blacklight/solr/server/solr/blacklight-core/conf
  name: blacklight-core