development:
    datahub_api_url: "http://datahub.box/api/v1/data/"
    datahub_oai_url: "http://datahub.box/oai/?verb=GetRecord&metadataPrefix=oai_lido&identifier="
testing:
    datahub_api_url: "http://datahub.box/api/v1/data/"
    datahub_oai_url: "http://datahub.box/oai/?verb=GetRecord&metadataPrefix=oai_lido&identifier="
production:
    datahub_api_url: "http://datahub.box/api/v1/data/"
    datahub_oai_url: "http://datahub.box/oai/?verb=GetRecord&metadataPrefix=oai_lido&identifier="
